url: https://tinekebanda.com
baseurl: /

# Site settings
title: Tineke Banda
email: tineke.banda@radboudumc.nl
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/tinekebanda
  - title: linkedin
    url: https://linkedin.com/in/tinekebanda
  - title: github
    url: https://github.com/tinekebanda


# Build settings
markdown: kramdown
permalink: pretty
